[package]
name = "local_server"
version = "0.1.0"
edition = "2021"

[dependencies]
pankosmia_web = "0.8.12"
rocket = { version = "0.5.0", features = ["json"] }
serde_json = "1.0.132"
tokio = "1.43.0"
